// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: DataPoints/server/data_point_stream.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Dolittle.TimeSeries.Runtime.DataPoints.Grpc.Server {

  /// <summary>Holder for reflection information generated from DataPoints/server/data_point_stream.proto</summary>
  public static partial class DataPointStreamReflection {

    #region Descriptor
    /// <summary>File descriptor for DataPoints/server/data_point_stream.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static DataPointStreamReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CilEYXRhUG9pbnRzL3NlcnZlci9kYXRhX3BvaW50X3N0cmVhbS5wcm90bxIl",
            "ZG9saXR0bGUudGltZXNlcmllcy5kYXRhcG9pbnRzLnNlcnZlchobZ29vZ2xl",
            "L3Byb3RvYnVmL2VtcHR5LnByb3RvGhpEYXRhVHlwZXMvZGF0YV9wb2ludC5w",
            "cm90bzJfCg9EYXRhUG9pbnRTdHJlYW0STAoET3BlbhIoLmRvbGl0dGxlLnRp",
            "bWVzZXJpZXMuZGF0YXR5cGVzLkRhdGFQb2ludBoWLmdvb2dsZS5wcm90b2J1",
            "Zi5FbXB0eSIAKAFCNaoCMkRvbGl0dGxlLlRpbWVTZXJpZXMuUnVudGltZS5E",
            "YXRhUG9pbnRzLkdycGMuU2VydmVyYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Protobuf.WellKnownTypes.EmptyReflection.Descriptor, global::Dolittle.TimeSeries.DataTypes.Protobuf.DataPointReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
