// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: DataPoints/server/data_point_processors.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Dolittle.TimeSeries.Runtime.DataPoints.Grpc.Server {

  /// <summary>Holder for reflection information generated from DataPoints/server/data_point_processors.proto</summary>
  public static partial class DataPointProcessorsReflection {

    #region Descriptor
    /// <summary>File descriptor for DataPoints/server/data_point_processors.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static DataPointProcessorsReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Ci1EYXRhUG9pbnRzL3NlcnZlci9kYXRhX3BvaW50X3Byb2Nlc3NvcnMucHJv",
            "dG8SJWRvbGl0dGxlLnRpbWVzZXJpZXMuZGF0YXBvaW50cy5zZXJ2ZXIaGkRh",
            "dGFUeXBlcy9kYXRhX3BvaW50LnByb3RvGixEYXRhUG9pbnRzL3NlcnZlci9k",
            "YXRhX3BvaW50X3Byb2Nlc3Nvci5wcm90bzKGAQoTRGF0YVBvaW50UHJvY2Vz",
            "c29ycxJvCgRPcGVuEjkuZG9saXR0bGUudGltZXNlcmllcy5kYXRhcG9pbnRz",
            "LnNlcnZlci5EYXRhUG9pbnRQcm9jZXNzb3IaKC5kb2xpdHRsZS50aW1lc2Vy",
            "aWVzLmRhdGF0eXBlcy5EYXRhUG9pbnQiADABQjWqAjJEb2xpdHRsZS5UaW1l",
            "U2VyaWVzLlJ1bnRpbWUuRGF0YVBvaW50cy5HcnBjLlNlcnZlcmIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Dolittle.TimeSeries.DataTypes.Protobuf.DataPointReflection.Descriptor, global::Dolittle.TimeSeries.Runtime.DataPoints.Grpc.Server.DataPointProcessorReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
