// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: DataPoints/server/output_stream.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Dolittle.TimeSeries.Runtime.DataPoints.Grpc.Server {

  /// <summary>Holder for reflection information generated from DataPoints/server/output_stream.proto</summary>
  public static partial class OutputStreamReflection {

    #region Descriptor
    /// <summary>File descriptor for DataPoints/server/output_stream.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static OutputStreamReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiVEYXRhUG9pbnRzL3NlcnZlci9vdXRwdXRfc3RyZWFtLnByb3RvEiVkb2xp",
            "dHRsZS50aW1lc2VyaWVzLmRhdGFwb2ludHMuc2VydmVyGhtnb29nbGUvcHJv",
            "dG9idWYvZW1wdHkucHJvdG8aGkRhdGFUeXBlcy9kYXRhX3BvaW50LnByb3Rv",
            "MlwKDE91dHB1dFN0cmVhbRJMCgRPcGVuEhYuZ29vZ2xlLnByb3RvYnVmLkVt",
            "cHR5GiguZG9saXR0bGUudGltZXNlcmllcy5kYXRhdHlwZXMuRGF0YVBvaW50",
            "IgAwAUI1qgIyRG9saXR0bGUuVGltZVNlcmllcy5SdW50aW1lLkRhdGFQb2lu",
            "dHMuR3JwYy5TZXJ2ZXJiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Protobuf.WellKnownTypes.EmptyReflection.Descriptor, global::Dolittle.TimeSeries.DataTypes.Protobuf.DataPointReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
