trigger:
- master

resources:
  repositories:
    - repository: templates
      type: github
      name: dolittle-tools/AzureDevOps
      endpoint: dolittle-tools

jobs:
- template: Source/Contracts/pipeline.yml@templates
  parameters:
    pipPackageName: 'dolittle-timeseries-runtime-contracts'
    nugetPackageName: 'Dolittle.TimeSeries.Runtime.Contracts'
    npmPackageName: 'dolittle/TimeSeries.Runtime.Contracts'
