// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Connectors/server/stream_connectors.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Dolittle.TimeSeries.Runtime.Connectors.Grpc.Server {

  /// <summary>Holder for reflection information generated from Connectors/server/stream_connectors.proto</summary>
  public static partial class StreamConnectorsReflection {

    #region Descriptor
    /// <summary>File descriptor for Connectors/server/stream_connectors.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static StreamConnectorsReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CilDb25uZWN0b3JzL3NlcnZlci9zdHJlYW1fY29ubmVjdG9ycy5wcm90bxIl",
            "ZG9saXR0bGUudGltZXNlcmllcy5jb25uZWN0b3JzLnNlcnZlchobZ29vZ2xl",
            "L3Byb3RvYnVmL0VtcHR5LnByb3RvGh9EYXRhUG9pbnRzL3RhZ19kYXRhX3Bv",
            "aW50LnByb3RvIlcKE1N0cmVhbVRhZ0RhdGFQb2ludHMSQAoKRGF0YVBvaW50",
            "cxgBIAMoCzIsLmRvbGl0dGxlLnRpbWVzZXJpZXMuZGF0YXBvaW50cy5UYWdE",
            "YXRhUG9pbnQycgoQU3RyZWFtQ29ubmVjdG9ycxJeCgRPcGVuEjouZG9saXR0",
            "bGUudGltZXNlcmllcy5jb25uZWN0b3JzLnNlcnZlci5TdHJlYW1UYWdEYXRh",
            "UG9pbnRzGhYuZ29vZ2xlLnByb3RvYnVmLkVtcHR5IgAoAUI1qgIyRG9saXR0",
            "bGUuVGltZVNlcmllcy5SdW50aW1lLkNvbm5lY3RvcnMuR3JwYy5TZXJ2ZXJi",
            "BnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Protobuf.WellKnownTypes.EmptyReflection.Descriptor, global::Dolittle.TimeSeries.Runtime.DataPoints.Grpc.TagDataPointReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Dolittle.TimeSeries.Runtime.Connectors.Grpc.Server.StreamTagDataPoints), global::Dolittle.TimeSeries.Runtime.Connectors.Grpc.Server.StreamTagDataPoints.Parser, new[]{ "DataPoints" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class StreamTagDataPoints : pb::IMessage<StreamTagDataPoints> {
    private static readonly pb::MessageParser<StreamTagDataPoints> _parser = new pb::MessageParser<StreamTagDataPoints>(() => new StreamTagDataPoints());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<StreamTagDataPoints> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Dolittle.TimeSeries.Runtime.Connectors.Grpc.Server.StreamConnectorsReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public StreamTagDataPoints() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public StreamTagDataPoints(StreamTagDataPoints other) : this() {
      dataPoints_ = other.dataPoints_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public StreamTagDataPoints Clone() {
      return new StreamTagDataPoints(this);
    }

    /// <summary>Field number for the "DataPoints" field.</summary>
    public const int DataPointsFieldNumber = 1;
    private static readonly pb::FieldCodec<global::Dolittle.TimeSeries.Runtime.DataPoints.Grpc.TagDataPoint> _repeated_dataPoints_codec
        = pb::FieldCodec.ForMessage(10, global::Dolittle.TimeSeries.Runtime.DataPoints.Grpc.TagDataPoint.Parser);
    private readonly pbc::RepeatedField<global::Dolittle.TimeSeries.Runtime.DataPoints.Grpc.TagDataPoint> dataPoints_ = new pbc::RepeatedField<global::Dolittle.TimeSeries.Runtime.DataPoints.Grpc.TagDataPoint>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Dolittle.TimeSeries.Runtime.DataPoints.Grpc.TagDataPoint> DataPoints {
      get { return dataPoints_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as StreamTagDataPoints);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(StreamTagDataPoints other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!dataPoints_.Equals(other.dataPoints_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= dataPoints_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      dataPoints_.WriteTo(output, _repeated_dataPoints_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += dataPoints_.CalculateSize(_repeated_dataPoints_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(StreamTagDataPoints other) {
      if (other == null) {
        return;
      }
      dataPoints_.Add(other.dataPoints_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            dataPoints_.AddEntriesFrom(input, _repeated_dataPoints_codec);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
