// Code generated by protoc-gen-go. DO NOT EDIT.
// source: DataPoints.Storage/Fabric/store.proto

package fabric

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
	system "system"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type StorageRequest struct {
	TimeseriesId         *system.Guid `protobuf:"bytes,1,opt,name=timeseriesId,proto3" json:"timeseriesId,omitempty"`
	Interval             float64      `protobuf:"fixed64,2,opt,name=interval,proto3" json:"interval,omitempty"`
	Retention            float64      `protobuf:"fixed64,3,opt,name=retention,proto3" json:"retention,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *StorageRequest) Reset()         { *m = StorageRequest{} }
func (m *StorageRequest) String() string { return proto.CompactTextString(m) }
func (*StorageRequest) ProtoMessage()    {}
func (*StorageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1610447e7845e9a1, []int{0}
}

func (m *StorageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StorageRequest.Unmarshal(m, b)
}
func (m *StorageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StorageRequest.Marshal(b, m, deterministic)
}
func (m *StorageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StorageRequest.Merge(m, src)
}
func (m *StorageRequest) XXX_Size() int {
	return xxx_messageInfo_StorageRequest.Size(m)
}
func (m *StorageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StorageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StorageRequest proto.InternalMessageInfo

func (m *StorageRequest) GetTimeseriesId() *system.Guid {
	if m != nil {
		return m.TimeseriesId
	}
	return nil
}

func (m *StorageRequest) GetInterval() float64 {
	if m != nil {
		return m.Interval
	}
	return 0
}

func (m *StorageRequest) GetRetention() float64 {
	if m != nil {
		return m.Retention
	}
	return 0
}

func init() {
	proto.RegisterType((*StorageRequest)(nil), "dolittle.timeseries.datapoints.storage.fabric.StorageRequest")
}

func init() {
	proto.RegisterFile("DataPoints.Storage/Fabric/store.proto", fileDescriptor_1610447e7845e9a1)
}

var fileDescriptor_1610447e7845e9a1 = []byte{
	// 288 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x91, 0x4f, 0x4b, 0xf3, 0x40,
	0x10, 0xc6, 0xdf, 0xf4, 0xc5, 0x7f, 0xab, 0x14, 0xdc, 0x83, 0x94, 0xe8, 0xa1, 0x14, 0x84, 0x5e,
	0x3a, 0x2b, 0xe9, 0xd9, 0x8b, 0x56, 0xc1, 0x9b, 0xa4, 0x9e, 0xbc, 0x6d, 0x9a, 0x69, 0x58, 0x48,
	0x76, 0xe2, 0xee, 0x44, 0xe8, 0xc5, 0x0f, 0xe4, 0xa7, 0x94, 0x64, 0xdb, 0x86, 0xe2, 0xc9, 0x63,
	0x26, 0xf9, 0xfd, 0x9e, 0x79, 0x32, 0xe2, 0x76, 0xa1, 0x59, 0xbf, 0x92, 0xb1, 0xec, 0x61, 0xc9,
	0xe4, 0x74, 0x81, 0xea, 0x59, 0x67, 0xce, 0xac, 0x94, 0x67, 0x72, 0x08, 0xb5, 0x23, 0x26, 0x39,
	0xcb, 0xa9, 0x34, 0xcc, 0x25, 0x02, 0x9b, 0x0a, 0x3d, 0x3a, 0x83, 0x1e, 0x72, 0xcd, 0xba, 0x0e,
	0xa8, 0x0f, 0x28, 0xac, 0x3b, 0x34, 0xbe, 0x2e, 0x88, 0x8a, 0x12, 0x55, 0x07, 0x67, 0xcd, 0x5a,
	0x61, 0x55, 0xf3, 0x26, 0xb8, 0xe2, 0x4b, 0xbf, 0xf1, 0x8c, 0x95, 0x2a, 0x1a, 0x93, 0x87, 0xd1,
	0xe4, 0x4b, 0x0c, 0xb7, 0xe1, 0x29, 0x7e, 0x34, 0xe8, 0x59, 0x26, 0xe2, 0xa2, 0x4f, 0x7a, 0xc9,
	0x47, 0xd1, 0x38, 0x9a, 0x9e, 0x27, 0x43, 0xd8, 0xef, 0xd1, 0xd2, 0xe9, 0xc1, 0x37, 0x32, 0x16,
	0xa7, 0xc6, 0x32, 0xba, 0x4f, 0x5d, 0x8e, 0x06, 0xe3, 0x68, 0x1a, 0xa5, 0xfb, 0x67, 0x79, 0x23,
	0xce, 0x1c, 0x32, 0x5a, 0x36, 0x64, 0x47, 0xff, 0xbb, 0x97, 0xfd, 0x20, 0xa9, 0xc4, 0x51, 0x9b,
	0x8f, 0x32, 0x17, 0x27, 0x8f, 0x64, 0x2d, 0xae, 0x58, 0x5e, 0x41, 0x28, 0x01, 0xbb, 0x12, 0xf0,
	0xd4, 0x96, 0x88, 0xef, 0xe1, 0x4f, 0xff, 0x02, 0x0e, 0x8b, 0x4d, 0xfe, 0xdd, 0x45, 0x0f, 0xf8,
	0x3e, 0x2f, 0xa8, 0xd7, 0x18, 0x52, 0xbd, 0x49, 0xf5, 0x26, 0xb5, 0x35, 0xa9, 0x60, 0xfa, 0x1e,
	0xcc, 0x16, 0x3b, 0xe4, 0xcd, 0x54, 0xb8, 0x0c, 0xc9, 0xbf, 0x0f, 0x08, 0xe1, 0x80, 0xd9, 0x71,
	0xb7, 0xf9, 0xfc, 0x27, 0x00, 0x00, 0xff, 0xff, 0xb8, 0x27, 0x3c, 0x59, 0xe4, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// StoreClient is the client API for Store service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type StoreClient interface {
	Connect(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (Store_ConnectClient, error)
}

type storeClient struct {
	cc *grpc.ClientConn
}

func NewStoreClient(cc *grpc.ClientConn) StoreClient {
	return &storeClient{cc}
}

func (c *storeClient) Connect(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (Store_ConnectClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Store_serviceDesc.Streams[0], "/dolittle.timeseries.datapoints.storage.fabric.Store/Connect", opts...)
	if err != nil {
		return nil, err
	}
	x := &storeConnectClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Store_ConnectClient interface {
	Recv() (*StorageRequest, error)
	grpc.ClientStream
}

type storeConnectClient struct {
	grpc.ClientStream
}

func (x *storeConnectClient) Recv() (*StorageRequest, error) {
	m := new(StorageRequest)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// StoreServer is the server API for Store service.
type StoreServer interface {
	Connect(*empty.Empty, Store_ConnectServer) error
}

// UnimplementedStoreServer can be embedded to have forward compatible implementations.
type UnimplementedStoreServer struct {
}

func (*UnimplementedStoreServer) Connect(req *empty.Empty, srv Store_ConnectServer) error {
	return status.Errorf(codes.Unimplemented, "method Connect not implemented")
}

func RegisterStoreServer(s *grpc.Server, srv StoreServer) {
	s.RegisterService(&_Store_serviceDesc, srv)
}

func _Store_Connect_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(empty.Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(StoreServer).Connect(m, &storeConnectServer{stream})
}

type Store_ConnectServer interface {
	Send(*StorageRequest) error
	grpc.ServerStream
}

type storeConnectServer struct {
	grpc.ServerStream
}

func (x *storeConnectServer) Send(m *StorageRequest) error {
	return x.ServerStream.SendMsg(m)
}

var _Store_serviceDesc = grpc.ServiceDesc{
	ServiceName: "dolittle.timeseries.datapoints.storage.fabric.Store",
	HandlerType: (*StoreServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Connect",
			Handler:       _Store_Connect_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "DataPoints.Storage/Fabric/store.proto",
}
