// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: DataPoints/Microservice/state.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Dolittle.TimeSeries.DataPoints.Microservice {

  /// <summary>Holder for reflection information generated from DataPoints/Microservice/state.proto</summary>
  public static partial class StateReflection {

    #region Descriptor
    /// <summary>File descriptor for DataPoints/Microservice/state.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static StateReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiNEYXRhUG9pbnRzL01pY3Jvc2VydmljZS9zdGF0ZS5wcm90bxIrZG9saXR0",
            "bGUudGltZXNlcmllcy5kYXRhcG9pbnRzLm1pY3Jvc2VydmljZRobZ29vZ2xl",
            "L3Byb3RvYnVmL2VtcHR5LnByb3RvGhpEYXRhVHlwZXMvZGF0YV9wb2ludC5w",
            "cm90byJPCg9EYXRhUG9pbnRzU3RhdGUSPAoKZGF0YVBvaW50cxgBIAMoCzIo",
            "LmRvbGl0dGxlLnRpbWVzZXJpZXMuZGF0YXR5cGVzLkRhdGFQb2ludDJpCgVT",
            "dGF0ZRJgCgZHZXRBbGwSFi5nb29nbGUucHJvdG9idWYuRW1wdHkaPC5kb2xp",
            "dHRsZS50aW1lc2VyaWVzLmRhdGFwb2ludHMubWljcm9zZXJ2aWNlLkRhdGFQ",
            "b2ludHNTdGF0ZSIAQi6qAitEb2xpdHRsZS5UaW1lU2VyaWVzLkRhdGFQb2lu",
            "dHMuTWljcm9zZXJ2aWNlYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Protobuf.WellKnownTypes.EmptyReflection.Descriptor, global::Dolittle.TimeSeries.DataTypes.DataPointReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Dolittle.TimeSeries.DataPoints.Microservice.DataPointsState), global::Dolittle.TimeSeries.DataPoints.Microservice.DataPointsState.Parser, new[]{ "DataPoints" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class DataPointsState : pb::IMessage<DataPointsState> {
    private static readonly pb::MessageParser<DataPointsState> _parser = new pb::MessageParser<DataPointsState>(() => new DataPointsState());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<DataPointsState> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Dolittle.TimeSeries.DataPoints.Microservice.StateReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public DataPointsState() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public DataPointsState(DataPointsState other) : this() {
      dataPoints_ = other.dataPoints_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public DataPointsState Clone() {
      return new DataPointsState(this);
    }

    /// <summary>Field number for the "dataPoints" field.</summary>
    public const int DataPointsFieldNumber = 1;
    private static readonly pb::FieldCodec<global::Dolittle.TimeSeries.DataTypes.DataPoint> _repeated_dataPoints_codec
        = pb::FieldCodec.ForMessage(10, global::Dolittle.TimeSeries.DataTypes.DataPoint.Parser);
    private readonly pbc::RepeatedField<global::Dolittle.TimeSeries.DataTypes.DataPoint> dataPoints_ = new pbc::RepeatedField<global::Dolittle.TimeSeries.DataTypes.DataPoint>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Dolittle.TimeSeries.DataTypes.DataPoint> DataPoints {
      get { return dataPoints_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as DataPointsState);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(DataPointsState other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!dataPoints_.Equals(other.dataPoints_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= dataPoints_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      dataPoints_.WriteTo(output, _repeated_dataPoints_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += dataPoints_.CalculateSize(_repeated_dataPoints_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(DataPointsState other) {
      if (other == null) {
        return;
      }
      dataPoints_.Add(other.dataPoints_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            dataPoints_.AddEntriesFrom(input, _repeated_dataPoints_codec);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
