// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: DataPoints.Storage/Fabric/store.proto
// </auto-generated>
// Original file comments:
// ---------------------------------------------------------------------------------------------
//  Copyright (c) Dolittle. All rights reserved.
//  Licensed under the MIT License. See LICENSE in the project root for license information.
// --------------------------------------------------------------------------------------------
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Dolittle.TimeSeries.DataPoints.Storage.Fabric {
  /// <summary>
  /// Represents the service for requesting storage of timeseries
  /// </summary>
  public static partial class Store
  {
    static readonly string __ServiceName = "dolittle.timeseries.datapoints.storage.fabric.Store";

    static readonly grpc::Marshaller<global::Google.Protobuf.WellKnownTypes.Empty> __Marshaller_google_protobuf_Empty = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Google.Protobuf.WellKnownTypes.Empty.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Dolittle.TimeSeries.DataPoints.Storage.Fabric.StorageRequest> __Marshaller_dolittle_timeseries_datapoints_storage_fabric_StorageRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Dolittle.TimeSeries.DataPoints.Storage.Fabric.StorageRequest.Parser.ParseFrom);

    static readonly grpc::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Dolittle.TimeSeries.DataPoints.Storage.Fabric.StorageRequest> __Method_Connect = new grpc::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Dolittle.TimeSeries.DataPoints.Storage.Fabric.StorageRequest>(
        grpc::MethodType.ServerStreaming,
        __ServiceName,
        "Connect",
        __Marshaller_google_protobuf_Empty,
        __Marshaller_dolittle_timeseries_datapoints_storage_fabric_StorageRequest);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Dolittle.TimeSeries.DataPoints.Storage.Fabric.StoreReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of Store</summary>
    [grpc::BindServiceMethod(typeof(Store), "BindService")]
    public abstract partial class StoreBase
    {
      public virtual global::System.Threading.Tasks.Task Connect(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::IServerStreamWriter<global::Dolittle.TimeSeries.DataPoints.Storage.Fabric.StorageRequest> responseStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for Store</summary>
    public partial class StoreClient : grpc::ClientBase<StoreClient>
    {
      /// <summary>Creates a new client for Store</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public StoreClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for Store that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public StoreClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected StoreClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected StoreClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual grpc::AsyncServerStreamingCall<global::Dolittle.TimeSeries.DataPoints.Storage.Fabric.StorageRequest> Connect(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Connect(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncServerStreamingCall<global::Dolittle.TimeSeries.DataPoints.Storage.Fabric.StorageRequest> Connect(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncServerStreamingCall(__Method_Connect, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override StoreClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new StoreClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(StoreBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_Connect, serviceImpl.Connect).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static void BindService(grpc::ServiceBinderBase serviceBinder, StoreBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_Connect, serviceImpl == null ? null : new grpc::ServerStreamingServerMethod<global::Google.Protobuf.WellKnownTypes.Empty, global::Dolittle.TimeSeries.DataPoints.Storage.Fabric.StorageRequest>(serviceImpl.Connect));
    }

  }
}
#endregion
