// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: DataPoints.Storage/Fabric/store.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Dolittle.TimeSeries.DataPoints.Storage.Fabric {

  /// <summary>Holder for reflection information generated from DataPoints.Storage/Fabric/store.proto</summary>
  public static partial class StoreReflection {

    #region Descriptor
    /// <summary>File descriptor for DataPoints.Storage/Fabric/store.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static StoreReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiVEYXRhUG9pbnRzLlN0b3JhZ2UvRmFicmljL3N0b3JlLnByb3RvEi1kb2xp",
            "dHRsZS50aW1lc2VyaWVzLmRhdGFwb2ludHMuc3RvcmFnZS5mYWJyaWMaG2dv",
            "b2dsZS9wcm90b2J1Zi9lbXB0eS5wcm90bxoRc3lzdGVtL2d1aWQucHJvdG8i",
            "WwoOU3RvcmFnZVJlcXVlc3QSJAoMdGltZXNlcmllc0lkGAEgASgLMg4uZG9s",
            "aXR0bGUuZ3VpZBIQCghpbnRlcnZhbBgCIAEoARIRCglyZXRlbnRpb24YAyAB",
            "KAEybQoFU3RvcmUSZAoHQ29ubmVjdBIWLmdvb2dsZS5wcm90b2J1Zi5FbXB0",
            "eRo9LmRvbGl0dGxlLnRpbWVzZXJpZXMuZGF0YXBvaW50cy5zdG9yYWdlLmZh",
            "YnJpYy5TdG9yYWdlUmVxdWVzdCIAMAFCZVozZ28uZG9saXR0bGUuaW8vdGlt",
            "ZXNlcmllcy9kYXRhcG9pbnRzL3N0b3JhZ2UvZmFicmljqgItRG9saXR0bGUu",
            "VGltZVNlcmllcy5EYXRhUG9pbnRzLlN0b3JhZ2UuRmFicmljYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Protobuf.WellKnownTypes.EmptyReflection.Descriptor, global::System.Protobuf.GuidReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Dolittle.TimeSeries.DataPoints.Storage.Fabric.StorageRequest), global::Dolittle.TimeSeries.DataPoints.Storage.Fabric.StorageRequest.Parser, new[]{ "TimeseriesId", "Interval", "Retention" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class StorageRequest : pb::IMessage<StorageRequest> {
    private static readonly pb::MessageParser<StorageRequest> _parser = new pb::MessageParser<StorageRequest>(() => new StorageRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<StorageRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Dolittle.TimeSeries.DataPoints.Storage.Fabric.StoreReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public StorageRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public StorageRequest(StorageRequest other) : this() {
      timeseriesId_ = other.timeseriesId_ != null ? other.timeseriesId_.Clone() : null;
      interval_ = other.interval_;
      retention_ = other.retention_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public StorageRequest Clone() {
      return new StorageRequest(this);
    }

    /// <summary>Field number for the "timeseriesId" field.</summary>
    public const int TimeseriesIdFieldNumber = 1;
    private global::System.Protobuf.guid timeseriesId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::System.Protobuf.guid TimeseriesId {
      get { return timeseriesId_; }
      set {
        timeseriesId_ = value;
      }
    }

    /// <summary>Field number for the "interval" field.</summary>
    public const int IntervalFieldNumber = 2;
    private double interval_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public double Interval {
      get { return interval_; }
      set {
        interval_ = value;
      }
    }

    /// <summary>Field number for the "retention" field.</summary>
    public const int RetentionFieldNumber = 3;
    private double retention_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public double Retention {
      get { return retention_; }
      set {
        retention_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as StorageRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(StorageRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(TimeseriesId, other.TimeseriesId)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Interval, other.Interval)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Retention, other.Retention)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (timeseriesId_ != null) hash ^= TimeseriesId.GetHashCode();
      if (Interval != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Interval);
      if (Retention != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Retention);
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (timeseriesId_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(TimeseriesId);
      }
      if (Interval != 0D) {
        output.WriteRawTag(17);
        output.WriteDouble(Interval);
      }
      if (Retention != 0D) {
        output.WriteRawTag(25);
        output.WriteDouble(Retention);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (timeseriesId_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(TimeseriesId);
      }
      if (Interval != 0D) {
        size += 1 + 8;
      }
      if (Retention != 0D) {
        size += 1 + 8;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(StorageRequest other) {
      if (other == null) {
        return;
      }
      if (other.timeseriesId_ != null) {
        if (timeseriesId_ == null) {
          TimeseriesId = new global::System.Protobuf.guid();
        }
        TimeseriesId.MergeFrom(other.TimeseriesId);
      }
      if (other.Interval != 0D) {
        Interval = other.Interval;
      }
      if (other.Retention != 0D) {
        Retention = other.Retention;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (timeseriesId_ == null) {
              TimeseriesId = new global::System.Protobuf.guid();
            }
            input.ReadMessage(TimeseriesId);
            break;
          }
          case 17: {
            Interval = input.ReadDouble();
            break;
          }
          case 25: {
            Retention = input.ReadDouble();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
