// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Connectors/runtime/pull_connectors.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Dolittle.TimeSeries.Connectors.Runtime {

  /// <summary>Holder for reflection information generated from Connectors/runtime/pull_connectors.proto</summary>
  public static partial class PullConnectorsReflection {

    #region Descriptor
    /// <summary>File descriptor for Connectors/runtime/pull_connectors.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static PullConnectorsReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CihDb25uZWN0b3JzL3J1bnRpbWUvcHVsbF9jb25uZWN0b3JzLnByb3RvEiZk",
            "b2xpdHRsZS50aW1lc2VyaWVzLmNvbm5lY3RvcnMucnVudGltZRoRc3lzdGVt",
            "L2d1aWQucHJvdG8aG2dvb2dsZS9wcm90b2J1Zi9FbXB0eS5wcm90bxonQ29u",
            "bmVjdG9ycy9ydW50aW1lL3B1bGxfY29ubmVjdG9yLnByb3RvGh9EYXRhUG9p",
            "bnRzL3RhZ19kYXRhX3BvaW50LnByb3RvIm8KDFdyaXRlTWVzc2FnZRIjCgtj",
            "b25uZWN0b3JJZBgBIAEoCzIOLmRvbGl0dGxlLmd1aWQSOgoERGF0YRgCIAMo",
            "CzIsLmRvbGl0dGxlLnRpbWVzZXJpZXMuZGF0YXBvaW50cy5UYWdEYXRhUG9p",
            "bnQiDQoLUHVsbFJlcXVlc3Qy5AEKDlB1bGxDb25uZWN0b3JzEnkKB0Nvbm5l",
            "Y3QSNS5kb2xpdHRsZS50aW1lc2VyaWVzLmNvbm5lY3RvcnMucnVudGltZS5Q",
            "dWxsQ29ubmVjdG9yGjMuZG9saXR0bGUudGltZXNlcmllcy5jb25uZWN0b3Jz",
            "LnJ1bnRpbWUuUHVsbFJlcXVlc3QiADABElcKBVdyaXRlEjQuZG9saXR0bGUu",
            "dGltZXNlcmllcy5jb25uZWN0b3JzLnJ1bnRpbWUuV3JpdGVNZXNzYWdlGhYu",
            "Z29vZ2xlLnByb3RvYnVmLkVtcHR5IgBCKaoCJkRvbGl0dGxlLlRpbWVTZXJp",
            "ZXMuQ29ubmVjdG9ycy5SdW50aW1lYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::System.Protobuf.GuidReflection.Descriptor, global::Google.Protobuf.WellKnownTypes.EmptyReflection.Descriptor, global::Dolittle.TimeSeries.Connectors.Runtime.PullConnectorReflection.Descriptor, global::Dolittle.TimeSeries.DataPoints.TagDataPointReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Dolittle.TimeSeries.Connectors.Runtime.WriteMessage), global::Dolittle.TimeSeries.Connectors.Runtime.WriteMessage.Parser, new[]{ "ConnectorId", "Data" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Dolittle.TimeSeries.Connectors.Runtime.PullRequest), global::Dolittle.TimeSeries.Connectors.Runtime.PullRequest.Parser, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class WriteMessage : pb::IMessage<WriteMessage> {
    private static readonly pb::MessageParser<WriteMessage> _parser = new pb::MessageParser<WriteMessage>(() => new WriteMessage());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<WriteMessage> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Dolittle.TimeSeries.Connectors.Runtime.PullConnectorsReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public WriteMessage() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public WriteMessage(WriteMessage other) : this() {
      connectorId_ = other.connectorId_ != null ? other.connectorId_.Clone() : null;
      data_ = other.data_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public WriteMessage Clone() {
      return new WriteMessage(this);
    }

    /// <summary>Field number for the "connectorId" field.</summary>
    public const int ConnectorIdFieldNumber = 1;
    private global::System.Protobuf.guid connectorId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::System.Protobuf.guid ConnectorId {
      get { return connectorId_; }
      set {
        connectorId_ = value;
      }
    }

    /// <summary>Field number for the "Data" field.</summary>
    public const int DataFieldNumber = 2;
    private static readonly pb::FieldCodec<global::Dolittle.TimeSeries.DataPoints.TagDataPoint> _repeated_data_codec
        = pb::FieldCodec.ForMessage(18, global::Dolittle.TimeSeries.DataPoints.TagDataPoint.Parser);
    private readonly pbc::RepeatedField<global::Dolittle.TimeSeries.DataPoints.TagDataPoint> data_ = new pbc::RepeatedField<global::Dolittle.TimeSeries.DataPoints.TagDataPoint>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Dolittle.TimeSeries.DataPoints.TagDataPoint> Data {
      get { return data_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as WriteMessage);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(WriteMessage other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(ConnectorId, other.ConnectorId)) return false;
      if(!data_.Equals(other.data_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (connectorId_ != null) hash ^= ConnectorId.GetHashCode();
      hash ^= data_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (connectorId_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(ConnectorId);
      }
      data_.WriteTo(output, _repeated_data_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (connectorId_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(ConnectorId);
      }
      size += data_.CalculateSize(_repeated_data_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(WriteMessage other) {
      if (other == null) {
        return;
      }
      if (other.connectorId_ != null) {
        if (connectorId_ == null) {
          ConnectorId = new global::System.Protobuf.guid();
        }
        ConnectorId.MergeFrom(other.ConnectorId);
      }
      data_.Add(other.data_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (connectorId_ == null) {
              ConnectorId = new global::System.Protobuf.guid();
            }
            input.ReadMessage(ConnectorId);
            break;
          }
          case 18: {
            data_.AddEntriesFrom(input, _repeated_data_codec);
            break;
          }
        }
      }
    }

  }

  public sealed partial class PullRequest : pb::IMessage<PullRequest> {
    private static readonly pb::MessageParser<PullRequest> _parser = new pb::MessageParser<PullRequest>(() => new PullRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<PullRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Dolittle.TimeSeries.Connectors.Runtime.PullConnectorsReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PullRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PullRequest(PullRequest other) : this() {
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PullRequest Clone() {
      return new PullRequest(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as PullRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(PullRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(PullRequest other) {
      if (other == null) {
        return;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
