// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Connectors/runtime/stream_connectors.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Dolittle.TimeSeries.Connectors.Runtime {

  /// <summary>Holder for reflection information generated from Connectors/runtime/stream_connectors.proto</summary>
  public static partial class StreamConnectorsReflection {

    #region Descriptor
    /// <summary>File descriptor for Connectors/runtime/stream_connectors.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static StreamConnectorsReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CipDb25uZWN0b3JzL3J1bnRpbWUvc3RyZWFtX2Nvbm5lY3RvcnMucHJvdG8S",
            "JmRvbGl0dGxlLnRpbWVzZXJpZXMuY29ubmVjdG9ycy5ydW50aW1lGhtnb29n",
            "bGUvcHJvdG9idWYvRW1wdHkucHJvdG8aH0RhdGFQb2ludHMvdGFnX2RhdGFf",
            "cG9pbnQucHJvdG8iVwoTU3RyZWFtVGFnRGF0YVBvaW50cxJACgpEYXRhUG9p",
            "bnRzGAEgAygLMiwuZG9saXR0bGUudGltZXNlcmllcy5kYXRhcG9pbnRzLlRh",
            "Z0RhdGFQb2ludDJzChBTdHJlYW1Db25uZWN0b3JzEl8KBE9wZW4SOy5kb2xp",
            "dHRsZS50aW1lc2VyaWVzLmNvbm5lY3RvcnMucnVudGltZS5TdHJlYW1UYWdE",
            "YXRhUG9pbnRzGhYuZ29vZ2xlLnByb3RvYnVmLkVtcHR5IgAoAUIpqgImRG9s",
            "aXR0bGUuVGltZVNlcmllcy5Db25uZWN0b3JzLlJ1bnRpbWViBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Protobuf.WellKnownTypes.EmptyReflection.Descriptor, global::Dolittle.TimeSeries.DataPoints.TagDataPointReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Dolittle.TimeSeries.Connectors.Runtime.StreamTagDataPoints), global::Dolittle.TimeSeries.Connectors.Runtime.StreamTagDataPoints.Parser, new[]{ "DataPoints" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class StreamTagDataPoints : pb::IMessage<StreamTagDataPoints> {
    private static readonly pb::MessageParser<StreamTagDataPoints> _parser = new pb::MessageParser<StreamTagDataPoints>(() => new StreamTagDataPoints());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<StreamTagDataPoints> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Dolittle.TimeSeries.Connectors.Runtime.StreamConnectorsReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public StreamTagDataPoints() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public StreamTagDataPoints(StreamTagDataPoints other) : this() {
      dataPoints_ = other.dataPoints_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public StreamTagDataPoints Clone() {
      return new StreamTagDataPoints(this);
    }

    /// <summary>Field number for the "DataPoints" field.</summary>
    public const int DataPointsFieldNumber = 1;
    private static readonly pb::FieldCodec<global::Dolittle.TimeSeries.DataPoints.TagDataPoint> _repeated_dataPoints_codec
        = pb::FieldCodec.ForMessage(10, global::Dolittle.TimeSeries.DataPoints.TagDataPoint.Parser);
    private readonly pbc::RepeatedField<global::Dolittle.TimeSeries.DataPoints.TagDataPoint> dataPoints_ = new pbc::RepeatedField<global::Dolittle.TimeSeries.DataPoints.TagDataPoint>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Dolittle.TimeSeries.DataPoints.TagDataPoint> DataPoints {
      get { return dataPoints_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as StreamTagDataPoints);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(StreamTagDataPoints other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!dataPoints_.Equals(other.dataPoints_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= dataPoints_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      dataPoints_.WriteTo(output, _repeated_dataPoints_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += dataPoints_.CalculateSize(_repeated_dataPoints_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(StreamTagDataPoints other) {
      if (other == null) {
        return;
      }
      dataPoints_.Add(other.dataPoints_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            dataPoints_.AddEntriesFrom(input, _repeated_dataPoints_codec);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
