// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: DataPoints/Runtime/data_point_stream.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Dolittle.TimeSeries.DataPoints.Runtime {

  /// <summary>Holder for reflection information generated from DataPoints/Runtime/data_point_stream.proto</summary>
  public static partial class DataPointStreamReflection {

    #region Descriptor
    /// <summary>File descriptor for DataPoints/Runtime/data_point_stream.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static DataPointStreamReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CipEYXRhUG9pbnRzL1J1bnRpbWUvZGF0YV9wb2ludF9zdHJlYW0ucHJvdG8S",
            "JmRvbGl0dGxlLnRpbWVzZXJpZXMuZGF0YXBvaW50cy5ydW50aW1lGhtnb29n",
            "bGUvcHJvdG9idWYvZW1wdHkucHJvdG8aGkRhdGFUeXBlcy9kYXRhX3BvaW50",
            "LnByb3RvMl8KD0RhdGFQb2ludFN0cmVhbRJMCgRPcGVuEiguZG9saXR0bGUu",
            "dGltZXNlcmllcy5kYXRhdHlwZXMuRGF0YVBvaW50GhYuZ29vZ2xlLnByb3Rv",
            "YnVmLkVtcHR5IgAoAUIpqgImRG9saXR0bGUuVGltZVNlcmllcy5EYXRhUG9p",
            "bnRzLlJ1bnRpbWViBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Protobuf.WellKnownTypes.EmptyReflection.Descriptor, global::Dolittle.TimeSeries.DataTypes.DataPointReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
