// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: DataPoints/Runtime/data_point_processors.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Dolittle.TimeSeries.DataPoints.Runtime {

  /// <summary>Holder for reflection information generated from DataPoints/Runtime/data_point_processors.proto</summary>
  public static partial class DataPointProcessorsReflection {

    #region Descriptor
    /// <summary>File descriptor for DataPoints/Runtime/data_point_processors.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static DataPointProcessorsReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Ci5EYXRhUG9pbnRzL1J1bnRpbWUvZGF0YV9wb2ludF9wcm9jZXNzb3JzLnBy",
            "b3RvEiZkb2xpdHRsZS50aW1lc2VyaWVzLmRhdGFwb2ludHMucnVudGltZRoa",
            "RGF0YVR5cGVzL2RhdGFfcG9pbnQucHJvdG8aLURhdGFQb2ludHMvcnVudGlt",
            "ZS9kYXRhX3BvaW50X3Byb2Nlc3Nvci5wcm90bzKHAQoTRGF0YVBvaW50UHJv",
            "Y2Vzc29ycxJwCgRPcGVuEjouZG9saXR0bGUudGltZXNlcmllcy5kYXRhcG9p",
            "bnRzLnJ1bnRpbWUuRGF0YVBvaW50UHJvY2Vzc29yGiguZG9saXR0bGUudGlt",
            "ZXNlcmllcy5kYXRhdHlwZXMuRGF0YVBvaW50IgAwAUIpqgImRG9saXR0bGUu",
            "VGltZVNlcmllcy5EYXRhUG9pbnRzLlJ1bnRpbWViBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Dolittle.TimeSeries.DataTypes.DataPointReflection.Descriptor, global::Dolittle.TimeSeries.DataPoints.Runtime.DataPointProcessorReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
