// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: DataPoints/Runtime/output_stream.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Dolittle.TimeSeries.DataPoints.Runtime {

  /// <summary>Holder for reflection information generated from DataPoints/Runtime/output_stream.proto</summary>
  public static partial class OutputStreamReflection {

    #region Descriptor
    /// <summary>File descriptor for DataPoints/Runtime/output_stream.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static OutputStreamReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiZEYXRhUG9pbnRzL1J1bnRpbWUvb3V0cHV0X3N0cmVhbS5wcm90bxIlZG9s",
            "aXR0bGUudGltZXNlcmllcy5kYXRhcG9pbnRzLnNlcnZlchobZ29vZ2xlL3By",
            "b3RvYnVmL2VtcHR5LnByb3RvGhpEYXRhVHlwZXMvZGF0YV9wb2ludC5wcm90",
            "bzJcCgxPdXRwdXRTdHJlYW0STAoET3BlbhIWLmdvb2dsZS5wcm90b2J1Zi5F",
            "bXB0eRooLmRvbGl0dGxlLnRpbWVzZXJpZXMuZGF0YXR5cGVzLkRhdGFQb2lu",
            "dCIAMAFCKaoCJkRvbGl0dGxlLlRpbWVTZXJpZXMuRGF0YVBvaW50cy5SdW50",
            "aW1lYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Protobuf.WellKnownTypes.EmptyReflection.Descriptor, global::Dolittle.TimeSeries.DataTypes.DataPointReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
